"""add role constraint, tz-aware timestamps, explicit task check constraints

Revision ID: 04e25d04f24a
Revises: 0405bcf97e7c
Create Date: 2026-08-28 01:30:47.949484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04e25d04f24a'
down_revision = '0405bcf97e7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_check_constraint('ck_users_role', "role IN ('admin', 'manager', 'member')")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('ck_users_role', type_='check')

    # ### end Alembic commands ###
